name: conda-environment-forbinder
channels:
  - conda-forge
dependencies:
  - python=3.6
  - notebook=6.0.1
  - numpy=1.17.1
  - click=7.0
  - scipy=1.4.1
  - pandas=0.25.3
  - matplotlib=3.1.1
  - ipywidgets=7.5.1